---
version: '2'
services:
  db:
    image: postgres:9.4.5
    environment:
      POSTGRES_PASSWORD: moderations
      POSTGRES_USER: moderations
      POSTGRES_DB: development_moderations
  moderations_web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_PASSWORD: moderations
      DB_USERNAME: moderations
      DB_DATABASE: development_moderations
      DB_HOST: db
      DB_PORT: 5432
      DB_POOL: 10

      #MIX_ENV: development
    volumes:
      - .:/app
    ports:
      #- "80:80"
      #- "443:443"
      - "4000:4000"
    links:
      - db:db
    depends_on:
      - db
